### ISSUE TITLE
Is the .ics file still used?

### ISSUE THREAD

**Issue by razzeee** [CTreffOS/ctreffos-webseite#7]
It seems to miss meetings in the future completely.

So:
1. There are no meetings
2. It's not supposed to have online meetings
3. It's not up to date

**Comment by razzeee** [comment]
So it might be 1. as I've tried this and the last week to catch the weekly Thursday meeting. But nobody showed up in jitsi.

**Comment by elanfer** [comment]
Thank you for your remark on this. Honestly, due to COVID-19 and changing regulations, we did not have regular meetings in the last time and scheduled them via chat and then mostly only for a small group. I now updated the ICS file, and we try to get back to a regular schedule. First with meetings every two weeks starting on the 30th. An E-Mail with all necessary information on this will be sent later to our public mailing list. I'm going to close this issue, please comment if there are further questions on this.
