### ISSUE TITLE
Does the freenode channel still exist?

### ISSUE THREAD

**Issue by razzeee** [CTreffOS/ctreffos-webseite#8]
Since everybody seems to have switched to libera.chat, is the IRC channel still on freenode?

**Comment by petvoigt** [comment]
On Sun, 05 Sep 2021 05:06:14 -0700
Kolja Lampe ***@***.***> wrote:

> Since everybody seems to have switched to libera.chat, is the IRC
> channel still on freenode? 
> 
> 

Yes, the channel at freenode is still in use. But traffic is very low
and it looks like I am the only participant for very long periods of
time. ;-)

You're right: Most channels have moved to libera.chat and we should move
as well. We will discuss this soon with the board. Moreover, I am not
sure, if our IRC channel will attract more participants or if we should
even drop our IRC channel. What is your opinion?

Regards,
Peter

**Comment by razzeee** [comment]
My opinion is switch to matrix :)

But not sure if most would be fine with that. Or if we would need to talk about using a different homeserver then matrix.org

Anyway, if you decide for IRC, I would like to link it to matrix.

**Comment by lkiesow** [comment]
+1 for Matrix

**Comment by petvoigt** [comment]
On Sun, 05 Sep 2021 08:16:28 -0700
Kolja Lampe ***@***.***> wrote:

> My opinion is switch to matrix :)
> 
> But not sure if most would be fine with that. Or if we would need to
> talk about using a different homeserver then matrix.org
> 
> Anyway, if you decide for IRC, I would like to link it to matrix.
> 

Thanks for your opinion. We will discuss it on the board.

My personal opinion: We should just drop IRC and use our own XMPP
server. Maybe you want to make a try - it's up and running for several
years now:
***@***.***?join

**Comment by razzeee** [comment]
In that case setting up https://matrix.org/docs/projects/bot/matter bridge might be cool

**Comment by petvoigt** [comment]
Unfortunately, your provided links currently seems invalid. Nevertheless, I've created a Matrix (and XMPP) test room with Matterbridge. Maybe you would like to join during the test phase: #pv_test:matrix.org. At this time I cannot foresee, if we will open an "official" Matrix room this way.

**Comment by razzeee** [comment]
https://matrix.org/docs/projects/bot/matterbridge
Sorry, seems like there was a stray space in there

**Comment by petvoigt** [comment]
Well, our IRC channel is history. We decided within our board to drop it immediately instead of moving it to LiberaChat. Main reason for this decision is the extremly low traffic in our IRC channel during the last few years.

Besides that, I've created a temporary Matrix room #pv_test:matrix.org which is currently bridged with Matterbridge to my private XMPP server. Main purpose is to evaluate the bridging capability of Matterbridge using the Matrix-XMPP bridge. Depending on the result we may or not offer a Matrix room on whatever server as a replacement for our current Telegram channel. Both the Matrix and the XMPP test room "pv_test" is public.
